name: Build and GitOps Update

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-app:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKER_USERNAME }}/go-app:${IMAGE_TAG}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Clone GitOps Repo
        run: |
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/mo7amedgom3a/go-app-gitops.git

      - name: Update Helm values.yaml
        run: |
          cd go-app-gitops/charts/go-app
          sed -i "s/tag:.*/tag: \"${IMAGE_TAG}\"/" values.yaml

      - name: Commit & Push GitOps Changes
        run: |
          cd go-app-gitops
          git config user.email "ci@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "chore: update image tag to ${IMAGE_TAG}"
          git push origin main
